language: android

jdk:
  - oraclejdk8

notifications:
  email: false

sudo: required

android:
  components:
    - tools
    - build-tools-29.0.0
    - android-29
    - extra-android-m2repository
    - extra-android-support

before_install:
 - chmod +x gradlew


script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
   
